[phases.setup]
nixPkgs = ["python311", "gcc", "musl", "openssl"]

[phases.install]
cmds = [
  "pip install -U pip",
  "pip install --no-cache-dir -r requirements.txt",
  "pip uninstall -y telethon",
  "pip install --no-cache-dir telethon==1.34.0",
  "pip install --no-cache-dir cryptg==0.4.0"
]

[phases.deploy]
cmds = ["python main.py"]

[start]
cmd = "python main.py"